### ISSUE TITLE
Android integration

### ISSUE THREAD

**Issue by edewit** [Napp/AeroGear-Push-Titanium#2]
Hi love your module, wanted to integrate it even more into the aerogear project if you don't mind. Maybe we could even remove the https://github.com/morinel/gcmpush dependency and replace it with a Titanium based version of the https://github.com/aerogear/aerogear-cordova-push wdyt?

**Comment by viezel** [comment]
yep, that is for sure possible. 
I was thinking about using the https://github.com/aerogear/aerogear-android-push and wrap it into a module.. but the GCM works fine for now. The upcomming version 1.3 will have geolocation support - at that point it will make sense to build a custom module.

**Comment by edewit** [comment]
I've done that already, shall I create a PR to use this instead? 
https://github.com/edewit/aerogear-titanium-push

**Comment by viezel** [comment]
you could.. but arent you missing the GCM topic support: https://github.com/morinel/gcmpush/blob/master/src/nl/vanvianen/android/gcm/GCMModule.java#L296-L306
and metric opening tracking from here: https://github.com/aerogear/aerogear-android-push/tree/master/aerogear-android-push/src/main/java/org/jboss/aerogear/android/unifiedpush/metrics

**Comment by edewit** [comment]
@viezel there is no topic support yet in UPS, but it will get there soon, and I just added metrics support. So nothing holding back this PR ;)

**Comment by viezel** [comment]
@edewit cool :+1: lets do this PR :)
